FROM ubuntu:bionic

RUN apt-get update
RUN apt-get install -y alsa
RUN apt-get install -y alsa-utils python3 python3-pip python3-dev mosquitto mosquitto-clients \ 
	&& pip3 install paho-mqtt \
	&& rm -rf /var/lib/apt/lists/*

WORKDIR /
COPY voice2audio.sh troy.wav /
CMD ./voice2audio.sh
